### ISSUE TITLE
Feature Request: Opening in temporary containers based on domain

### ISSUE THREAD

**Issue by cherti** [stoically/firefox-add-on-temporary-containers#10]
It would be cool if the feature existing with `Mouse Clicks per Website` could be extended to also trigger when entering a domain into the address bar, allowing to contain websites similar to the feature "alwasys open in $container" of Mozilla's original Container Add-on without explicitly creating a container for this website. This would be especially useful for websites that should be contained into their own container, but are only visited rarely, not justifying their own container.
The `Mouse Clicks per Website`-feature currently works with clicking links, but there is no option to trigger a temporary container by entering specific domains into an uncontained tab.

**Comment by stoically** [comment]
So I guess you use the Add-on with `Automatic Mode` deactivated? I think it should be no big problem to implement a "Always open in Temporary Container per Website" and make it available in the preferences.

Just a side-note: With `Automatic Mode` disabled Mouse Clicks have no effect whatsoever currently, tho I plan to decouple that.

**Comment by cherti** [comment]
> So I guess you use the Add-on with Automatic Mode deactivated?

Yes, that is correct. This feature is of course only relevant with `Automatic Mode` deactivated.

Didn't know about the Mouse Click no-effect thing, just starting out with the add-on, thanks for the hint!

**Comment by stoically** [comment]
Well, it depends, you can open "No Container" tabs using keyboard shortcuts in Automatic Mode - and I'm not sure whether the new preference should have an effect in those "No Container" tabs too.

**Comment by cherti** [comment]
If you mean Tabs not in a container by No-container-Tabs, then I would argue that it should, because from my point of view the purpose of this feature would be the containment of websites into temporary containers, regardless of their origin.

**Comment by stoically** [comment]
I agree. Just published version 0.17 with the feature. If something is not working as expected please let me know.

**Comment by stoically** [comment]
Oh, and btw, the new version also includes the decoupling of "Automatic Mode" and "Mouse Clicks" - so you could configure Mouse Clicks even with Automatic Mode disabled if you would want to.

**Comment by cherti** [comment]
That was fast, thank you very much! :)

**Comment by cherti** [comment]
Works perfectly fine as far as I can tell so far, thank you very much.

I personally would like an option (checkbox or so) to also apply this logic for things already opened in a different container, so that if those sites are linked on a site in a certain container, they still are opened it a separate standalone temporary container. That would be quite beautiful! :)

**Comment by stoically** [comment]
Depends on https://github.com/mozilla/multi-account-containers/pull/1095 and #25

**Comment by stoically** [comment]
Just published version 0.59 with change to the "Always open in" feature:
- If a "Always open in" Website pattern loads in a tab that doesn't match the pattern, a new Temporary Containers gets created. This is also true for permanent containers - unless the checkbox in the preferences for that pattern to "Allow in permanent Containers" is ticked. The migration path for existing patterns is to allow loading in permanent containers
- If the Website is also assigned with Multi-Account Containers nothing happens (MAC 6.0.0 is required, if the Website is assigned with versions below 6.0.0 unexpected behavior will happen)

Hope you like it. Let me know if something doesn't work as expected.

**Comment by cherti** [comment]
So far this works really excellent! Thank you very much, precisely the piece I missed in the Containers-Ecosystem so far to leverage its maximum potential.

Thank you very much for taking care of realizing! If I encounter any bugs, I will file them, but I haven't noticed any so far in production.

**Comment by cherti** [comment]
Do you think it's feasable to have an option to open the specified pages in a temporary container even if they are already in a container? i.e. I have a website in a container, that is linking to an external page that is listed for temporary containers, currently that one gets opened in the container I'm already in. It would be cool if this one would be opened in a temporary container instead, unconditionally quarantining certain pages into their own container.

Just a question of feasability, if not, I'm already happy enough with what you have built so far. :)

**Comment by stoically** [comment]
Could you elaborate on how your current preferences are and what you would expect them to do different?

If you open a website now, regardless if in a container, tmp container or no container and click on a link which matches a Website pattern that is configured as "Always per Website" (and the "Allow in permanent containers" not ticked), then this link/website will open in a new Temporary Container.

**Comment by cherti** [comment]
hm, sorry for the noise. Somehow I thought that this feature did not work when the starting site was already inside of a container. However, the site I noticed that now behaves exactly as desired, the link leads to the external page being opened in a temorary container as it should be (and you describe). Seems like my memory played tricks on me, nevermind, everything works like a charm. :)

**Comment by stoically** [comment]
No problem, happy it works!

Though, I noticed, that it opens the site multiple times in a new Temporary Containers in that exact scenario. Gonna fix that. :)

**Comment by stoically** [comment]
The multiple times reopening thing is now a thing of the past with version 0.63

**Comment by cherti** [comment]
Thank you very much,keep up the good work! :)
