### ISSUE TITLE
Instead of random colors/icons, can you cycle them?

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/firefox-add-on-temporary-containers#11]
Instead of the option to allow random colors/icons, can you cycle through them so there are only duplicates once they have all been used up?

More important for color than icon, IMO.

**Comment by stoically** [comment]
Yeah, I can do that, good idea!

**Comment by stoically** [comment]
Just published version 0.17 with evened out random container colors. If something is not working as expected please let me know.
