### ISSUE TITLE
Stops working in manual mode

### ISSUE THREAD

**Issue by sfeary** [stoically/firefox-add-on-temporary-containers#12]
Seems something went wrong in the code re-factoring unfortunately. In manual mode if I select "Random Container Color" or select to reuse available numbers no container is opened. Leaving them in their default state and it works again.

Also something I've noticed in extensions is the "Alt+C" shortcut doesn't seem to work on MacOS for some reason?

**Comment by stoically** [comment]
Thanks for reporting and sorry for breaking. Unfortunately this affected a part of the code which is hard to cover with test (external triggering of Event Listeners), but I will look into adding tests for that, so it won't happen again - since that's like the core functionality that should always work.

Version 0.18 with the fix is published. Please let me know if there's still something not working as expected - especially the Alt+C combo, that should work under MacOS.

**Comment by sfeary** [comment]
Thanks for the prompt fix, the key combo however is still a no go on MacOS. Works fine under Windows and Linux so it's something odd on the Mac side as always.

**Comment by stoically** [comment]
Do you by chance know of a Add-on that uses a keyboard shortcut involving the Alt key that works MacOS? I sadly can't find anything that indicates that Add-ons should do something different for MacOS.

**Comment by stoically** [comment]
Just had someone testing it on MacOS 10.12.6 / Firefox 57.0.1 and it works for them. :thinking:

**Comment by sfeary** [comment]
Very strange! I've 10.11.6 and 10.13.2 machines running 57.0.2 and they both do nothing. I tested a fresh profile with just your extension installed with the same result. The only other extension I know that I saw the ALT-C combo was Containers on the go and like yours it didn't work there either. 

I could understand if there was an issue with my profile but as I said it exhibits it with a fresh profile so I'm stumped but sure it's a minor thing and if it's only me then don't worry about it!

**Comment by stoically** [comment]
Oh well, if it doesn't work with other Add-ons too, then that sounds like a Firefox/Webextensions bug - you could maybe report it to the Firefox Team then? Nothing I can do about it, sorry!

Do the other shortcuts Alt+N or Alt+Shift+C work?

**Comment by sfeary** [comment]
When I did a little digging it turns out to be a keyboard locale issue, my system keyboard is set to Irish and if I change it to U.S. or British it works as expected. So it's an OS issue but thanks for all the help!
