### ISSUE TITLE
Cmd-Click on Mac instead of Ctrl-Left_Mouse

### ISSUE THREAD

**Issue by gthzl** [stoically/firefox-add-on-temporary-containers#14]
Hi! Thanks you very much for this extremely useful tool!

On a Macbook you have to use Cmd+Click instead of middle click or Ctrl+Click to open a link in a new tab. However, Cmd+Click never opens the link in a new temporary container, even if in automatic mode and Ctrl+"Left Mouse" and "Middle Mouse" is set to "Always". I am guessing that you have to check for a different keycode (cmd-key instead of ctrl-key).

It would be nice, if you can look into this at some time.

I wish you a merry xmas!

G.

**Comment by stoically** [comment]
Hey, happy you like it!

Oh, didn't know it's Cmd+Left Click on MacOS. Fortunately I can [detect that too](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey) - so I'm going to implement it. Thanks for letting me know!

**Comment by stoically** [comment]
Just to be sure that I implement the correct behavior - could you Cmd+Click on the "clickme" on the right side [on this page](https://jsfiddle.net/tLby297d/) and copy&paste me what's shown in the alert box? That would help me! Thanks.

**Comment by gthzl** [comment]
Thanks for looking into it!

The alert box shows: {"button":0,"metaKey":true,"ctrlKey":false}

**Comment by stoically** [comment]
Thanks for the info.

Just published version 0.19 with Cmd+Click support. Let me know if it doesn't work as expected.

I'm curious - does MacOS not support MiddleMouseClick on Links at all?

**Comment by gthzl** [comment]
Works like a charm!

Thanks a lot for the quick fix! Again, great idea with the add-on. Will use it a lot.
