### ISSUE TITLE
Feature Request: Exclude Domains

### ISSUE THREAD

**Issue by rue** [stoically/firefox-add-on-temporary-containers#16]
I will almost always want to use a container when opening links—auto mode is great for that!

However, on certain sites on which I need to log in (like Github), I often open several tabs. I’d prefer those to be in the same container so that I don’t lose my session, and handle possible issues with other extensions.

Auto + exclude list (+ current domain match) seems to me the perfect balance between security and usability.

**Comment by stoically** [comment]
Hi,

in general you can assign the Website to "Always open in $Container" (and optionally "Remember my choice") - so it will always open in that Container.

However, if you're opening the new Tabs by Ctrl/Cmd+LeftMouse or MiddleMouse Clicking on Links and want to prevent Temporary Containers from acting you can go into the Preferences, Mouse Clicks, Per Website and configure on which Website Mouse Clicks should `Never` do anything.

If that doesn't cover what you're looking for, please let me know what your exact scenario is.

Also, if you know about compatibility issues with other Add-ons, please let me know so that I can look into fixing them.

Thanks!

**Comment by rue** [comment]
Hm, got it. The workaround with Multi-Account Containers _sort of_ works, but the UI is a bit cumbersome (plus there’s the double-tab problem I think there’s another issue for).

My use case is to use temporary containers _everywhere_, with the exception that certain whitelisted domains are allowed to open links in the current container, typically to support sessions—for example, I want to be able to open a new tab for the Multi-Account Containers github link in your reply without having to sign in again in that tab.

Or I’m on Twitter, and want to open a couple people’s timelines in separate tabs.

Basically any site where you want to open multiple tabs in the same context, but get rid of that context once you close the last tab. (Plus with Temporary Containers you get automatic support for being able to do multiple such sessions for any given site as long as you explicitly start a new container.)

So here’s what I’d like:

0. In Temporary Containers prefs, a whitelist of urls/domains to Open in Same Container
1. I add *github.com to that list
2. Auto mode on
3. In whatever container I am, if I click to open a new window, the Open in Same Container list is checked. I.e. if I click a github.com link, it will open the link _in the container I am already in_.
4. If I click a link not listed in OiSC, a new temporary container is created just like currently.
5. (Optional) Domain Matching. Same as 3. but only open in the current container if the current domain matches the link I’m clicking (i.e. I’m on github.com/foo/bar and click github.com/bar/baz).

Does that help to see what I’m getting at? I’ll probably get to it at some point myself, but I figured you’ll be able to do it much faster if you find the idea useful.

**Comment by stoically** [comment]
> (plus there’s the double-tab problem I think there’s another issue for).

There should be no double-tab problem together with Multi-Account Containers. The handling of intervention from MAC is [a bit fuzzy](https://github.com/mozilla/multi-account-containers/issues/929#issuecomment-348376375), but it should work. If you can reproduce that bug I'd really appreciate if you could tell me how (in a new Issue or here).

> In whatever container I am, if I click to open a new window, the Open in Same Container list is checked. I.e. if I click a github.com link, it will open the link in the container I am already in.

If you just Left Click a Link, it should always open in the same container. If you RightClick on a Link and select the first thing in the Context Menu ("Open Link in New $Container Tab") it should open the Link in the same Container. If you're opening the new Tabs by Ctrl/Cmd+LeftMouse or MiddleMouse Clicking on Links and want that the Links open in the same Container (without having MAC do the job), you can already do this by going into the Preferences and configuring Mouse Clicks:

`Preferences` > `Mouse Clicks`
Global: Setting `Ctrl+Left` and/or `Middle Mouse` to `Never` would *always* open Links in the same/current container. `Only if the clicked Link is not the same as the Website` would achieve what you described in `5.`
Per Website: Same as in global, just that the preference would only be active on a certain website. Like you could have Mouse Clicks globally configured to `Always` open Temporary Containers, but make a `Per Website` rule for `github.com` to `Only if the clicked Link is not the same as the Website` which would achieve `5.` only on github.com.

Not sure what other ways there would be to open links - if I'm missing something make sure to let me know!

**Comment by stoically** [comment]
Also, if you would like to achieve `3.` (open clicked Link always in same container, but just on github.com) for Ctrl/Cmd+T and/or MiddleMouse Clicks, the settings would be `Mouse Clicks` > `Per Website` > `github.com` & `Never`

**Comment by stoically** [comment]
>  if I click to open a new window

I just realized that. If you literally mean open a *new window*, that would be RightClick on a link and select "Open in a new window" in the Context Menu or Shift+Left Click on a link.

If you're going over the Context Menu it'll try to open the Link in a new "No Container" Tab in the new Window - with Automatic Mode it'll turn it into a Temporary Container. In this case I'd suggest you open a new Issue with MAC and ask for a feature to "Open Link in New Window $Container Tab".

If you're going over Shift+Left Click, that isn't currently supported by Temporary Containers but I could look into supporting it if that's your actual use-case?

**Comment by rue** [comment]
Sorry, I did mean tab earlier instead of window.

Context menu’s Open in $Container + MAC sort of almost does what I want, enough to get by for now. I’ll see if have the time to whip up a PR for a streamlined implementation.

Feel free to close this or leave it open, whichever works for you. Thanks!

**Comment by stoically** [comment]
So, for my understanding: do the Preferences work but are just to cumbersome / not streamlined enough for you? Or do the Preferences not cover your use-case? If the latter, could please explain again *how* do you open an Link? Thanks!

**Comment by rue** [comment]
Sorry, missed the reply! Yes, essentially it would be a more streamlined way of doing it within this extension (using all tab-opening mechanisms).

But it seems I’ve gotten used to using MAC in tandem with this extension and the two work pretty well together, so I think keeping the two separate is the right choice!
