### ISSUE TITLE
Open a new tab as the last tab

### ISSUE THREAD

**Issue by ghmv** [stoically/firefox-add-on-temporary-containers#19]
New tabs are always opened next to the active tab. That may not be desirable behavior. There should be at least a setting for opening tabs as the last tab if they are not opened from the link (i.e. Clicking the "Temporary Containers"-Icon and Pressing the Alt+C Shortcut).

**Comment by stoically** [comment]
The default behavior in Firefox for *new* tabs is to open them at the last position (to the right). If they currently not open at the last position for you, then you might want to check if you have Add-ons installed or Firefox configurations that affect the behavior.

If you want clicked links to open at the last position too, there's the [browser.tabs.insertRelatedAfterCurrent config setting](https://support.mozilla.org/en-US/questions/1185405).

By the way: if you open an issue on a project that you can use for free and is free software, you might want to consider whether "There should be at least a setting" is the appropriate formulation.

**Comment by ghmv** [comment]
I have no problems with standard new tabs, they are always opened at the last position (by a click or ctrl-t). But tabs opened by clicking "Temporary Containers"-Icon are always opened next to the active tab. It is not caused by any other addon – the behavior is the same even on the clean Firefox Nightly. (And addon similar to yours Containers On The Go opens new tabs also at the last position.)
(I'm sorry if you fell offended.)

**Comment by ghmv** [comment]
Well, in Nightly after switching on and again off Automatic mode (which I don't use), it started to behave as you described and is expected (all tabs are opened at the last position). But I use Developer edition and this trick didn't help – even Automatic mode doesn't work at all now. Maybe I used some addon which made some important setting – but turning off any addon doesn't help now.

**Comment by stoically** [comment]
Ah, now I see what you mean. Indeed the Icon/Alt+C Shortcut should behave like the Firefox default and open the New Tab at the last position. I'm gonna look into implementing it. Personally I only use Ctrl+T with Automatic Mode (one of the reasons I've developed the Add-on in the first place), so I never realized that. Thanks for letting me know!

**Comment by stoically** [comment]
Fixed with just published version 0.20
