### ISSUE TITLE
New tab immediately closes when url is container-pinned

### ISSUE THREAD

**Issue by schnittchen** [stoically/firefox-add-on-temporary-containers#21]
I'm using FF 57.0.4 with "Firefox Multi-Account Containers" (5.0.1) and this addon (0.20).

When I open a new tab and enter a URL for a domain for which I checked the "always open in <container name>" option, the tab immediately closes.
The same happens when clicking a link to a URL with this option, in a way that would open it in a new tab (middle-click IIRC, and target="_blank" links).

**Comment by stoically** [comment]
Hi, version 0.20 has a regression bug and it was actually only available for an hour or so. Could you please test again with version 0.22? Sorry about that!

I've also opened [a PR](https://github.com/mozilla/multi-account-containers/pull/1095) with Multi-Account Containers that, if it gets merged, should prevent problems with closing tabs completely.

**Comment by schnittchen** [comment]
Thank you, looks like that was it.
