### ISSUE TITLE
Remove /en-US/ from Mozilla links

### ISSUE THREAD

**Issue by anewuser** [stoically/firefox-add-on-temporary-containers#22]
Please remove `/en-US/` from the description of this repository and from the links in README.md, so that users will see the addons site in their default language.

**Comment by stoically** [comment]
Didn't know that's even possible. Done, thanks for the hint.

**Comment by anewuser** [comment]
Yeah, and actually just https://addons.mozilla.org/addon/temporary-containers/ works too, and automatically redirects the user to a different branded version of the site (/firefox/, /seamonkey/, /android/, or /thunderbir/ ) depending on the user-agent. Since this is a Firefox-only extension, you don't need to bother with it.
