### ISSUE TITLE
Add a Key to open in default "no container" in automatic mode

### ISSUE THREAD

**Issue by nodje** [stoically/firefox-add-on-temporary-containers#35]
Hi,

this is great stuff I love it!
I want to use it on an everyday basis. This combined with the standard container was the missing piece for a safe surfing.
I stumble up on a problem though: I still want to have access to a regular default "no container" or "main container" for convenience. This is possible with FF containers.
But with your TempContainer ext. in  automatic mode (which I want because it's especially useful with external program) there seem to be no way to open links in default no container.

Or did I miss it? 
Juts a shortcut key would be perfect.

**Comment by stoically** [comment]
Hi, happy you like it!

You can open links in No Container tabs by right-clicking, then "Open Link in New Container Tab" -> "No Container". Keyboard shortcuts to open No Container tabs are  <kbd>Alt</kbd>+<kbd>N</kbd> (Tab) or  <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>C</kbd> (Window).

Hope that helps.
