### ISSUE TITLE
Doesn't work with FF 52.5.0 ESR

### ISSUE THREAD

**Issue by qerberoz** [stoically/firefox-add-on-temporary-containers#4]
In FF 52.5.0 ESR a new link starts to open, then immediately disappears.

**Comment by stoically** [comment]
Published a Hotfix with Version 0.4 - that should solve the problem. Sorry about that!

If you still see the problem please let me know.

**Comment by stoically** [comment]
Just tested this with FF 52 ESR and doesn't work at all. Gonna publish new versions as minimum version FF 57 until I find the time to test other versions as well. Thanks for reporting.

**Comment by girst** [comment]
i believe containers was a feature of ff54

**Comment by stoically** [comment]
According to the [API Doc](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities) Containers were introduced with FF53 (with FF57 they added events - but I don't use those). I've changed the minimum version accordingly to FF53 - can't possibly do anything about it, sorry.

**Comment by stoically** [comment]
Just tested FF53-56 without luck. Only FF56 did *something* - but nowhere near functional. So I guess minimum version is FF57 for now.
