### ISSUE TITLE
Why use alt-p ?

### ISSUE THREAD

**Issue by quentm74** [stoically/firefox-add-on-temporary-containers#41]
Alt-p is use by default to pin / unpin tabs... this is too useful for me so I add to disable your great extension 😢

**Comment by stoically** [comment]
Which Operating System and Firefox Version are you using? I can't reproduce Alt+P being used by default to Pin/Unpin Tabs on Windows and Ubuntu.

**Comment by stoically** [comment]
Either way - I'll provide feature in the preferences where all available keyboard shortcuts can be disabled.

**Comment by quentm74** [comment]
Wow yes I forgot it was an addon I installed ! So I'm waiting for the "disabled" idea. 
Thanks for the quick answer 👍

**Comment by stoically** [comment]
Would you mind to share which Add-on causes this?

**Comment by anewuser** [comment]
Shortcuts with the <kbd>Alt</kbd> key have been known to cause problems in different keyboard layouts too: 

https://github.com/gorhill/uBlock/issues/2723
https://github.com/gorhill/uBlock/issues/2783
https://github.com/gorhill/uBlock/issues/3031

I don't think they mention the letters you used , but this is a good hint to avoid defaulting shortcuts to <kbd>Alt</kbd> + letter.

**Comment by stoically** [comment]
Good to know. But every keyboard shortcut will have some conflict somewhere - so the only really viable solution is to support disabling keyboard shortcuts and providing other means of accessing the feature. Unfortunately with WebExtensions in Firefox there's no chance to let the user rebind keyboard shortcuts.

**Comment by stoically** [comment]
Just published version 0.36 that lets you disable shortcuts in the advanced preferences.

Also, as long as you didn't gave the history permission under advanced it'll no longer open a new tab with Alt+P (opened a normal tab before that).

Hope you like it. Let me know if something isn't working as expected.
