### ISSUE TITLE
Consider asking users before enabling the automatic mode

### ISSUE THREAD

**Issue by anewuser** [stoically/firefox-add-on-temporary-containers#48]
I know that you've created this extension with the idea of making it automatic by default, but this can be too confusing for new users who just want a Private Tab or Containers on the Go replacement and don't know that the automatic mode can be disabled: https://github.com/Infocatcher/Private_Tab_WE/issues/1#issuecomment-362914961.

Users who do want it could be pointed to the settings page, and eventually you could add a landing page asking if it should be enabled on the first run.

**Comment by stoically** [comment]
Yeah, I agree that having an Add-on that disrupts the normal UX in a browser so hard can be really confusing. And I guess a lot of people [deactivate](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/statistics/usage/status/?last=30) for that reason. I don't know the ratio for other Add-ons, but it seems like a lot.

I'm bit torn though, my personal goal for this Add-on is and was to push the agenda of enhancing privacy. And with disable Automatic Mode it's really just a Private Window replacement. Either way, a landing page to opt-out of Automatic Mode is a really good idea and should be done sooner than later.

**Comment by anewuser** [comment]
> with disabled Automatic Mode by default it's really "just" an enhanced Private Window replacement. 

Well, not exactly, since all users regardless of their settings will be opening temp containers much more often than they opened private windows, and new containers are isolated from each other, unlike old private tabs.

**Comment by stoically** [comment]
> Well, not exactly, since all users regardless of their settings will be opening temp containers much more often than they opened private windows

Why do you assume / how do you know they use tmp tabs / private tabs more often than private windows?

> and new containers are isolated from each other

That's what I meant with "enhanced", yeah :D

**Comment by anewuser** [comment]
This is just an assumption based on how much more practical it is to have everything in the same window instead of changing windows all the time... and people installing the extension must already be inclined to like something like that.

**Comment by stoically** [comment]
> and people installing the extension must already be inclined to become frequent users.

I guess that's true. On the other hand there's the question, how many people get convinced to really enhance their privacy by using isolation when confronted by that default behavior? Without the default behavior they might never think about it. And people that don't manage to use the Automatic Mode or disable it, "only" lose a convenient way to open "private tabs".

**Comment by stoically** [comment]
Btw, not sure if you saw - but I changed the Add-on About-Text so that the very first thing is:

> By default the Temporary Containers Add-on will overwrite your standard ways of opening Tabs : instead of opening the Tab in No Container, it will open the Tab in a freshly created Temporary Container. If you don't want that, you have to disable "Automatic Mode" in the Add-ons options.

**Comment by stoically** [comment]
One could also make the comparison that Cookie AutoDelete doesn't automatically clean by default so users have time to whitelist cookie so they don't lose their logins - and that's what essentially happening if you are forced into the "Automatic Mode". The difference is that you would have to do that anyway with containers (unless there'd be a feature copy cookies over and stuff, but that sounds even harder to communicate UX wise)

**Comment by stoically** [comment]
Actually, now that I thought about it. Maybe that's a possible solution: If Automatic Mode is active and you browse to a website where cookies are detected in the default container, then show a dialog along the lines of "Looks like you have cookies for this website in your default container. Is this a website where you want to be logged in? Click here to copy the cookies to this container [dropdown] or No, I don't want to login here, delete the cookies".

No clue if it's technical possible, just an idea.

**Comment by jrie** [comment]
Hello. I haven't looked into the functionality to "copy"/"transfer" cookies from one tab to another in detail. But from what I know right now, it should be possible.

As some kind of reading about cookie "transfer":
Thats the Firefox cookie object definition, which is retrieved on "browser.cookie.get" (getter) functions:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/Cookie

And here is the opposing "set" function:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/set

So, yes, by reading the linked pages, I would say it is completely possible to do so, without touching a single file of the browser itself.

As for the logged-in state, in case of Flag Cookies, it then should be possible to "transfer" "keyed" / "logged in" (profile) cookies from one tab to another as the user can tell, "which cookies" are fine to transfer. This would be option 1.

Option 2: Open a view, tab1 name on the left, in the middle the cookie names and values with there permissions" on the right tab2 to transfer to. And below a "transfer logged in" and "transfer everything" (into tab2).

**Comment by anewuser** [comment]
This is getting more and more complicated. Private Tab was popular for just adding a button to open a private tab and not changing anything else. People liked Containers on the Go for the same reason - and negative comments just mentioned its not being open source.

My humble suggestion for you is to focus on the landing page and keep replying to questions and comments actively to motivate people to keep using the extension. Advanced users can already turn automatic mode on and use the workarounds you've mentioned.

After it gains traction and the bugs with MAC are fixed, users who get used to it with automatic mode off may eventually give it a try, and there will already  be tutorials and videos and TV interviews with you explaining how to use properly without losing their saved logins. :)

I get all your points, but the average user will still get annoyed or confused if they have to change too many options and thing don't work as expected anymore after installing the extension. Moving from just regular tabs to new containers on every tab is like getting used to Notepad and suddenly having Excel with complex formulas in your face.

You can can also help people's privacy by contributing to https://github.com/uBlockOrigin/uAssets/issues, which incidentally has started receiving recipes for uMatrix (https://github.com/uBlockOrigin/uAssets/tree/master/recipes). The next version will come with these as a subscription to automatically unbreak popular sites.

**Comment by stoically** [comment]
@jrie 

> So, yes, by reading the linked pages, I would say it is completely possible to do so

That's great, thanks for looking into it!

> As for the logged-in state, in case of Flag Cookies

I think both options sound good. The way Flag Cookies currently is designed, I would say the profile feature aims at more advanced users that want fine granular control over cookies; and a way to manage them across container boundaries would be a really good fit.

@anewuser 

> This is getting more and more complicated. Private Tab was popular for just adding a button to open a private tab and not changing anything else.

Personally I don't see how a really simple designed "transfer (all) cookies and open this site in a permanent container to login" dialog adds to the complexity. It would ease the on-boarding, imho, even for advanced users.

Private Tab will come back sooner or later - and with it the feature of just adding a button for a private window in a tab (just with the added bonus of possible container boundaries this time).

> After it gains traction and the bugs with MAC are fixed, users who get used to it with automatic mode off may eventually give it a try

Hopefully we see the MAC pull request merge soon. And personally, I still think people are not willing to change stuff they're already used to. At what point would you want to try to convince people to try "Fully isolated tab browsing" if not when they're installing the Add-on?

> and there will already be tutorials and videos and TV interviews 

Yeah, like all the other Free Software devs that are regularly on TV. Especially with something as popular as the container feature of Firefox. :)

> I get all your points, but the average user will still get annoyed or confused if they have to change too many options

I understand that - and maybe, probably this Add-on will not gain much traction - especially if an alternative comes along that doesn't try to push enhanced privacy in their face. But while I'm at it, I'll try to do what I personally feel is the right thing to do.

> You can can also help people's privacy by contributing to

There are **a lot** of great Free Software projects out there that aim to enhance or fight for peoples privacy. And I really appreciate all the work people put into it. Without we'd be lost in a proprietary world. My personal main focus (and where I invest the most time) is on [redecentralization](https://github.com/redecentralize/alternative-internet).

> I personally will be equally glad with anything you add or remove

Really glad that you like the Add-on and about all the input so far! You seem really active in the OpenSource Community and that's great.

**Comment by stoically** [comment]
Another thing that might be a compromise between the two options is, that if the Dialog shows that detects Cookies in No Container - it could also give the choice to deactivate Automatic Mode there.

**Comment by jrie** [comment]
From what I follow the conversation: The main issue with Temporary Containers is, you are enforcing some rules on the user by install.

From what I understand, there is no gentle way to introduce the features. Its, as said earlier, a "all in" or "all out" - once your add-on is installed, it nests itself quite deeply in the workflow, and this needs a training time for every new user, just "checking it out to see if it fits".

My suggestion would be - introduce the user to the new features!

Say: "You opened your first tab in a temporary container" -> "this means...."

So, the transition and the usability to work with your add-on is made gentle. You are providing the user upfront with information, what is "possible" and "what not", while trying to make use of it.

You can do so once, if no "checkbox is clicked" like "I understand.. dont annoy me anymore with this information".

But overall, this would gently introduce everything, so people can say how they want to make use of it.
If you are keen, another idea would be, to "configure along the way" meaning, a user can choose any setting, as he starts getting notified. Depending how this is possible of course. I think its not an option to have a "simple" notifcations asking the user for directions.

But something like this, would be a start.

**Comment by stoically** [comment]
> My suggestion would be - introduce the user to the new features!

You're right, a full-blown introduction/learning system would be awesome, but I guess also *a lot* of work

> I just want to add - you change the way, the user is using the browser

Well, the feature comes from Mozilla and is basically inspired by using profiles / private windows heavily. I just try to do what I think would be an useful additional step. But you're right, it'd require people to get more involved - and of course there are enough that don't care that much, which isn't necessarily bad, but it's a thing.


Anyway, https://github.com/stoically/firefox-add-on-temporary-containers/issues/49 is what I came up with and what kind of could be something that helps. It also features a prominent "I just want a Private Tab replacement"-Option. I think it will require a fair amount of work, but I guess it could be worth it. If you feel like it, you're of course invited to let me know what you think of the concept.

**Comment by jrie** [comment]
> You're right, a full-blown introduction/learning system would be awesome, but I guess also a lot of work

It doens't have to be "full-blown" - you just want to inform about the basic concept. I would guess.
So you keep the user informed on what is going on.

This might be tedious at first place, but imagine yourself - you install something, and it "entirely" wraps up on what you know about browsing. Without information and guidance, this could lead to a bad experience.

I will check out your link to issue #49 so. 👍

**Comment by stoically** [comment]
After thinking about it a bit - I guess it's actually the right decision to disable Automatic Mode per default as long as there's nothing like #49 or something comparable in place. I still think it's the right thing to do and try to "convince" people to make "the best" out of the Add-on - but it's not easy to understand without something that tells users what's going on. To expect that people actually read and understand the informations upfront is - well - optimistic. And those that *do* read the informations, are well capable of enabling it themselves.

So until some sort of easy onboarding is in place, the Automatic Mode and all Mouse Clicks will be disabled by default.

**Comment by stoically** [comment]
Published version 0.38 with the change.

**Comment by jrie** [comment]
In case of Multi-Account-Containers, if you have this add-on installed, you click and hold the "+" button to open a new tab, a menu is displayed to tell in what kind of container to open a new tab in.

Maybe a configurable (switch on/off in options) menu/dialog can be shown after clicking the "+" once - which allows the user to select to open either as default/private or temporary container?

And maybe its even possible to show a note or some information - what the container will do and which functionality provide versus the others options? Or something along that lines.

I'm thinking, this way, you can still offer the function to make use of Temporary Containers, but leaving the user the choice, whats favorable for the particular website they want to visit.
And if they start to like use of the Temporary containers with there benefits, as you offer, they can flip the option in the add-on settings to enable them as default. This could also be mentioned in that menu, maybe.
