### ISSUE TITLE
Only use temporary container when explicitly asked to

### ISSUE THREAD

**Issue by girst** [stoically/firefox-add-on-temporary-containers#5]
Hi, I'm coming from the thread over at mozilla/multi-account-containers#929. Thanks for creating this extension!

I'd love to be able to only use a temporary container when I want to (which is relatively rarely). Containers-on-the-go implements what I feel is the optimal workflow: keep tab openings as-is and add a toolbar button (which can be moved inside the tab bar) to open a temporary container. (It also adds a context menu entry for opening "this link" in one and a shortcut (alt+c))

**Comment by stoically** [comment]
Hey,

thanks for taking the time to open the Issue!

I absolutely plan to give users of the Add-on the possibility to configure the behaviour of when and how new Temporary Containers should get created. As soon as I start to work on the Preferences Feature that's gonna be the focus.

Personally I feel like that the default should maximize the usage of Temporary Containers to support the notion of trying to minimize tracking using Cookies/LocalStorage. Of course there's still fingerprinting - but I hope that besides blocking Canvas by default with FF58, we also will see more opportunities to make Containers even more tracking proof - and if users at that point are already comfortable with having disposable Containers most of time, that would be a benefit, at least that's what I like to believe.

So - should Ctrl+T or clicking Links from external applications open disposable Containers? I personally think so, yes. Or do I miss something obvious from a privacy or UI/UX point of view that speaks against it? I'd absolutely be interested in hearing your opinion on it!

**Comment by girst** [comment]
> So - should Ctrl+T or clicking Links from external applications open disposable Containers?

privacy-vice this would be the optimum, but ux-wise I don't think so. I expect to be in my 'trusted' environment (with cookies and such present) unless I make the conscious decision to open a non-trusted website. (i know this is subjective, but I feel this is they less-intrusive way for many)

also, by using your own hotkey, the workaround with closing and reopening tabs can be avoided.

**Comment by stoically** [comment]
I can see that, yeah. Although there's the "Always open in $Container" feature - which would essentially whitelist your "trusted environment" while blacklisting everything else. But I guess you're right that blacklisting by default and then whitelist what you need isn't what the majority wants. I'll keep that in mind when implementing Preferences.

Blocking and Reopening is unfortunately the only way to do it - there should imo really be a way to override the default Shortcuts. If I'm not mistaken that was possible with legacy Add-ons.

**Comment by stoically** [comment]
Just published Version 0.8. You can now disable "Automatic Mode" in the (rudimental) Add-On Preferences - doing so will only open new Temporary Containers when clicking Alt+C or the Temporary Container Icon (per default in the TabStrip).

Hope that helps. If you have further suggestions make sure to let me know. Cheers.

**Comment by girst** [comment]
This is perfect! thanks a lot!

**Comment by stoically** [comment]
Totally forgot about that Context Menu Entry when RightClicking Links. Now available with Version 0.9 too.
