### ISSUE TITLE
Pocket integration broken

### ISSUE THREAD

**Issue by HeikoAdams** [stoically/firefox-add-on-temporary-containers#52]
- Temporary Containers Version: 0.39
- Firefox Version: 58.0.1
- Operating System + Version: Fedora 27

### Actual behavior
Currently getpocket.com is allways opened in a temporary container which forces me to login everytime I want to see my pocket-list or add something to pocket.

### Expected behavior
get-pocket.com should be blacklisted for opening in a temporary container otherwise pocket integration is broken.

**Comment by stoically** [comment]
I'd say that getpocket.com is like any other website and thus the "How to stay logged in on some websites in Automatic Mode?" from the readme applies. Do you feel like it should open in no container by default?

**Comment by HeikoAdams** [comment]
Yes, because if I lock down getpocket in a default container it also doesn't work on pages which are locked into other containers. So it should be decontained by default, IMHO

**Comment by stoically** [comment]
Ok, I see now what you mean. You really only can login to pocket in the default container, not in a container at all (to get the Firefox UI working, that is).

https://github.com/mozilla/multi-account-containers/issues/824

> Treat URLs that are part of the browser UI as privledged and not able to be assigned ever

Gonna implement something that tries to decontain getpocket.com per default. If it's assigned with Multi-Account Containers that wont work tho. Thanks for letting me know.

**Comment by stoically** [comment]
As a workaround until it's implemented, in case you didn't know: disable Automatic Mode, sign into Pocket, reactivate Automatic Mode to get the UI working - and then assign getpocket.com to a container and login there too to be able to "View List"

**Comment by stoically** [comment]
Just published version 0.41 which ignores getpocket.com requests. It does not however decontain getpocket everywhere, e.g. when a link somwhere is clicked. It works for logging in with the UI integration and clicking on "View List" though. Let me know if something doesn't work as expected.
