### ISSUE TITLE
Version 0.43 borked it

### ISSUE THREAD

**Issue by Gitoffthelawn** [stoically/firefox-add-on-temporary-containers#54]
- Temporary Containers Version:  0.43
- Firefox Version: 59.0beta9

Everything working great until v0.43.  Now left-clicking on links results in them never getting resolved.  :(

**Comment by stoically** [comment]
Thanks for letting me know so fast. Deactivated version 0.43. Doesn't happen for me with Firefox 58 unfortunately. Gonna test it with Firefox 59. Could you please provide a debug log?

`about:debugging`, Check Debugging checkbox, Click "debug" under Temporary Containers, `log.DEBUG = true` into console and enter. Now click a link and copy&paste everything in the console. That would be really helpful.

**Comment by stoically** [comment]
Was able to reproduce it with Firefox58 and Firefox59. Thanks so much @Gitoffthelawn - I had probably never noticed.

**Comment by Gitoffthelawn** [comment]
You're welcome... was just posting the debug log! :)

**Comment by stoically** [comment]
Just published version 0.44 with the fix (and of course a test for it - that should never happen again, d'oh). Thanks again!

**Comment by Gitoffthelawn** [comment]
You're welcome!  It's working well now with 0.44.  :)
