### ISSUE TITLE
Temporarily deactivating the extension deletes all permanent containers / contexts / domains

### ISSUE THREAD

**Issue by derMart** [stoically/firefox-add-on-temporary-containers#578]
- Temporary Containers Version: 1.9.2
- Firefox Version: 99.0

### Actual behavior
- install extension
- manage containers -> add permanent container named test
- deactivate extension
- activate extension
- test container is deleted

### Expected behavior
- install extension
- manage containers -> add permanent container named test
- deactivate extension
- activate extension
- test container should be there

I had the impression that the extension just manages the built in firefox feature of the containers (or contexts or whatever the correct mozilla term for these domains are). I realized though, that as described above deactivating and activating the extension again completely deletes all the containers / contexts / domains which I have created. That is unexpected and should not happen.

best
Martin

**Comment by stoically** [comment]
Expected behavior. If you want to retain container data you have to keep at least one Add-on with the container permission active. The Add-on manager should warn you tho. Either way, it's not something TC can do anything about, unfortunately.

**Comment by derMart** [comment]
Ok, thanks for the answer. No there was no warning. Data was just deleted. I will file a bug on firefox. It should not be expected behaviour to unneccesary delete this data. Also the container feature should not be automatically deactivated by Firefox. Just doesn't make any sense. But I see, nothing temporary containers can do about.

**Comment by Gitoffthelawn** [comment]
@derMart For the Bugzilla issue you are going to file: I think it would be best for Firefox to give the user a choice and simply ask whether or not all container data should be deleted in this situation.  Deleting data without notice or storing data the user thinks is is deleted are obviously both no-no's... especially since Firefox is marketed as being privacy-oriented.
