### ISSUE TITLE
tmp container number no longer starts counting at tmp1

### ISSUE THREAD

**Issue by aDreamEater** [stoically/firefox-add-on-temporary-containers#586]
- Temporary Containers Version: 1.9.2
- Firefox Version: 101.0.1

Issue: The first tmp container opened is always tmp5 instead of tmp1, and tmp1 through tmp4 are never generated.
I'm pretty sure I know _why_ this is happening, but I don't know how to fix it.
I have four permanent containers, which I suspect is the reason why the tmp# count starts at tmp5.

In settings it is set to [automatic mode], as well as [reuse available numbers]. For some reason, changing that to [keep counting until browser restart] does make it start counting at tmp1 instead of starting at tmp5.

this might be related to #578 as I disabled all my add-ons to debug something, and when I turned them all on again this issue had started occurring, as well as me having all my permanent containers revert to their unconfigured default.
Disabling multi-account containers and temporary containers one at a time to see if it was an add-on prioritization order issue didn't do anything, and I'm reluctant to try turning them both off at the same time and lose my permanent containers again, (see #578), so I thought I'd ask for advice first.

**Comment by stoically** [comment]
Tried to reproduce with a FF 101.0.1 (latest stable), fresh profile and just installing TC and enabling automatic mode and reuse available numbers. Opening a new tab then starts at tmp1 as expected. Could you try with a fresh profile as described in the [issue template](https://github.com/stoically/temporary-containers/issues/new/choose)?

**Comment by aDreamEater** [comment]
Fresh profile could not reproduce. For some reason exporting settings, then uninstalling and reinstalling add-on got rid of the problem though, so no longer an issue. I should have tried that first. Sorry to bother you.

**Comment by stoically** [comment]
No worries. Glad it now works as expected for you. :+1:
