### ISSUE TITLE
FR: temporary disable Isolation with a timeout.

### ISSUE THREAD

**Issue by mhtrinh** [stoically/firefox-add-on-temporary-containers#592]
Currently, you can enable/disable isolation from TC icon. This is great for some crappy website (eg: #585) or some payment website that tend to bounce around few time !
User will have to disable Isolation for couple minute, time to fill in your credit card etc and then enable back Isolation.

The issue is sometime I forget to enable back Isolation, and start navigating all in the same container !

It would be great to have a button that disable TC Isolation for a define period (like 5min) and pop up warning telling the user that Isolation will be back on. 

Thanks for this wonderful addon !!! My counter soon have 6 digits !!

**Comment by stoically** [comment]
In the TC preferences under Advanced > Isolation you can configure a timeout. Hope that helps.

tmp100000 soon 👀

**Comment by stoically** [comment]
There's also a keyboard shortcut to disable isolation. Personally prefer it over the icon.

**Comment by mhtrinh** [comment]
Hell yeah !! 
Did not know that !! That's exactly what I was looking for !! Thanks !!!

**Comment by mhtrinh** [comment]
> There's also a keyboard shortcut to disable isolation. Personally prefer it over the icon.

It happen very very rarely for me so I won't bother to remember the keyboard shortcut :-P 
And because it happen rarely, I tend to forget to enable back Isolation ...
