### ISSUE TITLE
seach for open tabs over all tabs doesn't work

### ISSUE THREAD

**Issue by michaeltraxler** [stoically/firefox-add-on-temporary-containers#594]
I run temporary-containers in automatic mode. Whenever I open a new tab I want to search for something, a web-site via a search engine, a link in my history or in my bookmarks but *also* in the title of the open tabs (I have many open!). This last point (search for open tabs) stops working as soon as I enable temporary containers. It works only for tabs which all use the same container.
Can this be enabled, that this search works over all open tabs, as it is the default in plain firefox?

**Comment by stoically** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1479858

**Comment by michaeltraxler** [comment]
That is a real pity, that they didn't fix this bug for ~4 years! This bug-fix/feature is quite needed I think and makes the usage of containers much less useful.... But you can not do anything about it :-(
