### ISSUE TITLE
Can't Uninstall the Addon 100% - Help!

### ISSUE THREAD

**Issue by geedogz** [stoically/firefox-add-on-temporary-containers#598]
Hi.. I uninstalled the addon from my firefox. But upon installing a 2nd time, I noticed that some settings were kept from the initial installation. How do i uninstall this addon 100%?

**Comment by stoically** [comment]
Hey, that sounds like an issue with your Firefox installation or profile. Normally uninstalling the add-on should get rid of the preferences. I'd try with a fresh profile and see if it happens there as well. If you want to reset the preferences, there's a reset button in the advanced preferences.

**Comment by geedogz** [comment]
Hi.. its not the ff profile. I tried this on a new profile and same thing happens. What do you suggest?

**Comment by stoically** [comment]
Could you describe which preferences exactly are not the way you expect?

**Comment by geedogz** [comment]
So after I reinstall, I see a list of "tmp containers' which didn't exist before when I installed it the 1st time.

**Comment by stoically** [comment]
Ah, then you're probably affected by #371. Closing as duplicate. Let me know if it turns out to be something different.
