### ISSUE TITLE
It messes with my permanent containers

### ISSUE THREAD

**Issue by pityalvarez** [stoically/firefox-add-on-temporary-containers#599]
- Temporary Containers Version:
- Firefox Version:

### Actual behavior
.. Breaking my permanent containers

### Expected behavior
.. Stop breaking my permanent containers

### Steps to reproduce

1. .. Website on a temporary container
2. .. Try to open that website in a permanent container
3. .. Come backs to step 1

### Notes
..

**Comment by stoically** [comment]
What exactly does it break, like what isn't working as expected? Which kind of configuration do you use in TC, or are you using the default configuration?

**Comment by xnuk** [comment]
Go to Preferences -> Advances -> General -> Reset Storage -> "Wipe local storage and reset it to default" and configure settings again may help.

In my case, all of containers are gone after restarting computer, so I made a new container A, but the container A is deleted after all tabs are closed. The extension "Temporary Containers" had previous information, so `tempContainersNumbers` includes container A's number, so it deleted again and again, I guess.

**Comment by pityalvarez** [comment]
I had to reset it to default. I probably pressed something i wasn't supposed to, but i just wanted to use automatic mode. I don't know if i can put my local file so someone tells me what is a common mistake.
