### ISSUE TITLE
Custom searches (like Startpage) using POST don't work

### ISSUE THREAD

**Issue by spastorino** [stoically/firefox-add-on-temporary-containers#60]
When you try to search by writing something in the url bar and your search engine is Startpage HTTPS, temporary containers end opening Startpage without any search.

I guess this is due to the fact that Startpage by default uses a POST to search, when temporary containers get in the middle of the process the POST query is lost.

**Comment by stoically** [comment]
Hi, I'm using startpage as search-engine in Firefox too. It works with the [official](https://www.startpage.com/eng/download-startpage-plugin.html?) and [this](https://addons.mozilla.org/firefox/addon/startpage-privacy-search-engin/) OpenSearch for me. Both use GET, not POST. Could you provide more information which search-engine you're exactly using? Thanks!

I'm not aware of any way to make the address bar search use POST - though, I would be interested in it. Although, when you click result-links on startpage, even when using GET, it'll strip query parameters. You can check by searching for "whatsmyreferer" and clicking the first result with the GET method.

**Comment by spastorino** [comment]
I don't remember anymore. I have switched to the official one. Thanks.

**Comment by r-a-y** [comment]
I ran into this issue, but you can workaround this by using the "Reopen New Tabs in Temporary Containers mode" for the "Automatic Mode" option.

**Comment by stoically** [comment]
@r-a-y Could you provide informations on how to reproduce this or how to use the address bar to start a search using POST?

**Comment by r-a-y** [comment]
You need to add a search with the POST method.

You can add one from the Mycroft Project site:
http://mycroftproject.com/search-engines.html?name=startpage

Add the ` Startpage + DuckDuckGo Suggest (HTTPS, POST)` engine.

Next, under `about:preferences`, click on "Search" and select this search engine either as your default or add a keyword to it by selecting it and pressing `F2`.

Then, run a search from the Awesome Bar with the new search engine.  The search will only work correctly if you set Automatic Mode to "Reopen New Tabs in Temporary Containers".

**Comment by stoically** [comment]
Ah, got it. First navigate to the [Startpage preferences](https://www.startpage.com/do/preferences), then click "Generate URL" and then "Custom plugin". Now searches are broken.

**Comment by stoically** [comment]
@r-a-y Thanks for providing the info and poking this Issue!

**Comment by r-a-y** [comment]
No problem!  The feature works, but only by using the "Reopen New Tabs in Temporary Containers" option.  

So it's not really a bug unless you think you can fix this in the default Automatic Mode option -- "Don't reopen new tabs in Temporary Containers but instead on Navigation".

This might be more work than it's worth though, especially since you can use the workaround.

**Comment by stoically** [comment]
It's interesting. For me POST searches don't work at all in containers. Even when trying in a permanent container - and with both plugins, the one from the URL you provided and directly from the Startpage Settings.

Tested with Firefox59.0b12 and Firefox 58.0.2 under Ubuntu 16.04 - care to share you OS/Firefox versions?

**Comment by r-a-y** [comment]
One other thing I forgot to mention is you need to set your homepage to the Firefox default and not using a custom addon to set a different page for your new tab homepage.

Let me know if that ends up working for you.

**Comment by stoically** [comment]
I've tried with a fresh profile (everything default) and only Multi-Account Containers. Seems like a case for Bugzilla. (Also tried with Windows10)

![post](https://user-images.githubusercontent.com/29637501/36649218-ab29e082-1a9b-11e8-8b81-f5b180d73fc2.gif)

**Comment by r-a-y** [comment]
In your GIF, you're not using your own Temporary Containers addon?

I'll try to do everything on a fresh profile when I have the chance so I can document the steps.

**Comment by stoically** [comment]
The GIF starts with a fresh profile.

**Comment by stoically** [comment]
Although, even if it would work with containers, it would not work with the "Don't reopen New Tabs in Temporary Containers" option for Automatic Mode as it currently is, that's correct. Because reopening in general only takes the GET URL that comes in and opens a new tab with it. So supporting that would indeed require coding.

**Comment by r-a-y** [comment]
Okay, so you have to set `browser.newtabpage.activity-stream.enabled` to `false` to get POST search working with Temporary Containers and MAC enabled.

Let me know if that works.

**Comment by stoically** [comment]
Can confirm, that works!

It also works when first navigating to a website and then doing the search.

**Comment by stoically** [comment]
For reference, here's the Bugzilla Ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1441058

**Comment by stoically** [comment]
@grenzor Just tested with Firefox Dev Edition 61.0b3 (64-bit) on Linux and searching with POST now works with and without containers for me

**Comment by grenzor** [comment]
Hmm, not sure why it's not working for me on 61 Beta. I add a Startpage search using POST method to the browser, search using the search bar and land on Startpage homepage with no search results in a temp container. Have to search again once in the temp container to be able to use POST. Can't see any TC settings that would be causing this either :S

**Comment by stoically** [comment]
@grenzor Which beta version are you testing? Maybe the change didn't land yet in yours?

**Comment by grenzor** [comment]
61.0b3 (64-bit)

**Comment by grenzor** [comment]
@stoically figured out why the POST search wasn't working for me. For some reason in order for POST search to work new tabs have to be opened in a temporary container first e.g. using the "Open new tab in container" button. If I just open the new tab using the default "+" Firefox tab button or CTRL+T and search directly from the new tab I have to search first (which lands on the SP homepage in a temporary container) then search again after I'm in the temporary container. I don't know if that's a bug or intended behavior but if #146 is fixed I think opening a new tab the default way and searching will work then.

**Comment by sheddup** [comment]
Can someone explain like I'm five how to get search to work, all it does is land on the homepage.
