### ISSUE TITLE
Counter goes up

### ISSUE THREAD

**Issue by boredsquirrel** [stoically/firefox-add-on-temporary-containers#603]
- Temporary Containers Version: 1.9.2
- Firefox Version: 105.0.1

### Actual behavior
The number `tmp1` e.g. always goes up, even if the old containers get deleted automatically.
This is a nice little counter of how often you used the extension, but I think if will get annoying after like 1000 cycles.

### Expected behavior
The lowest number resets to one if no other containers are existent.

**Comment by stoically** [comment]
Check the general add-on preferences, you can configure the counter there to your expected behavior.

**Comment by boredsquirrel** [comment]
> Check the general add-on preferences, you can configure the counter there to your expected behavior.

found it myself, awesome settings
