### ISSUE TITLE
Tab container indicator color palettte too bright

### ISSUE THREAD

**Issue by tr37ion** [stoically/firefox-add-on-temporary-containers#61]
With dark Mozilla theme the provided tab colors are too light. Is it someho possible to disable coloring at all or getting a way darker color palette instead?

![image](https://user-images.githubusercontent.com/1538617/36605439-01503a4c-18c1-11e8-9d2f-1bf78ba9fa0d.png)

And/or change/move the indicator to the top of each bar? 

![image](https://user-images.githubusercontent.com/1538617/36606285-897cbc72-18c3-11e8-9506-5bb85ba05501.png)

**Comment by stoically** [comment]
Hi,

open `about:profiles`, click on "root directory" for your active profile, open or create the `chrome` folder, create `userChrome.css` in it, with the content:

```css
[data-identity-color="red"] {
  --identity-tab-color: #000000 !important;
  --identity-icon-color: #000000 !important;
}
```

Adjust `#000000` to your liking. `"red"` can any color you can set in the preferences, so you can overwrite different colors. Restart browser to see the changes. 

Source: https://www.reddit.com/r/unixporn/comments/78m6t1/oc_firefox_dark_theme/

Pro-Tip: Click the Firefox Menu, Select "Web Developer", Select "Browser Toolbox", Confirm the Dialog with OK. The Element-Picker (Top-Left) can select any Firefox Menu and reveal the underlying CSS that you can overwrite with `userChrome.css`

Hope that helps
