### ISSUE TITLE
Issue with programmatically created Pinned Tabs

### ISSUE THREAD

**Issue by ed1111** [stoically/firefox-add-on-temporary-containers#62]
I have Temporary Containers 0.58 and PersistentPin 1.0.1 installed into FF58.0.2.

Since installing Temporary Containers, on opening FF pinned tabs open unpinned as regular tabs.

Expected behavior with PersistentPin installed is for pinned tabs to remain as pinned tabs when FF is reopened.

**Comment by stoically** [comment]
Programmatically created tabs should indeed keep the pinned state. Will look into it, thanks for reporting.

**Comment by stoically** [comment]
Just published version 0.59 with the fix. Let me know if something still doesn't work as expected.
