### ISSUE TITLE
"Asterisk" Wildcard prevents login on any site

### ISSUE THREAD

**Issue by chrunchyjesus** [stoically/firefox-add-on-temporary-containers#64]
If I add `*` to websites, that should always be opened in temporary containers, I won't be able to login on any site because the site refresh would open a new container. Do you think it is a case that needs special handling?

I quite like this behavior as a feature and would love for it to stay. Since I do not know whether it is actually intended or not I thought I should at least mention it here.

**Comment by stoically** [comment]
Hi, this is actually not intended behavior. As long as the website stays "inside the website pattern" no new Temporary Container should be opened. Thanks for letting me know.

**Comment by stoically** [comment]
Just published version 0.63 with the fix. Let me know if something still doesn't work as expected.

**Comment by chrunchyjesus** [comment]
It is fixed now. Thank you for this awesome add-on!
